// Builds the files to copy into Google Apps Script (apps-script/build/):
//   Code.gs         the server, one file (from apps-script/src)
//   index.html      the web app, one file (web/src with apps-script/client)
//   appsscript.json the project manifest
// Usage: npm run build:apps-script
import { createHash } from 'node:crypto';
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { build as esbuild } from 'esbuild';
import { build as vite } from 'vite';

const here = (path) => fileURLToPath(new URL(path, import.meta.url));

// Code.gs and index.html get the same version, a hash of what's in them, so
// the same code always builds the same files and doGet can tell if the two
// pasted files don't match (see VERSION in src/main.ts).
const VERSION = '__TORETTO_VERSION__';
const stamp = (text, version) => text.replaceAll(VERSION, version);
// Windows checks files out with CRLF line endings: build the same bytes everywhere.
const normalizeLineEndings = (text) => text.replace(/\r+\n/g, '\n');

// ---- Code.gs -----------------------------------------------------------------
// One IIFE (Apps Script has no modules), lowered to syntax its V8 runs, plus
// plain functions Apps Script can call by name (the page, triggers, the editor).
export async function buildServer(version) {
  const server = await esbuild({
    entryPoints: [here('./src/main.ts')],
    bundle: true,
    format: 'iife',
    globalName: 'Toretto',
    target: 'es2019',
    platform: 'neutral',
    mainFields: ['module', 'main'],
    alias: { '@shared': here('../shared') },
    minifyWhitespace: true,
    minifySyntax: true,
    legalComments: 'none',
    write: false,
    logLevel: 'warning',
  });
  // The functions go first, setup at the top: the editor lists them in order
  // in the menu next to Debug. "use strict" stays the file's first statement.
  const strict = '"use strict";';
  const bundle = server.outputFiles[0].text;
  if (!bundle.startsWith(strict)) throw new Error('Expected the bundle to start with "use strict"');
  const code =
    `// Toretto Scheduling for Google Apps Script, version ${VERSION}. Generated by\n` +
    `// apps-script/build.mjs: paste the whole file into Code.gs; don't edit it here.\n` +
    `// First time: pick "setup" in the menu next to Debug, above, and click Run.\n` +
    `${strict}\n` +
    ENTRY_POINTS +
    bundle.slice(strict.length);
  return version ? stamp(normalizeLineEndings(code), version) : normalizeLineEndings(code);
}

const ENTRY_POINTS = `
/** Run once after pasting this file, and again after each update. */
function setup() { return Toretto.setup(); }
/** The web app (Deploy → New deployment → Web app). */
function doGet(e) { return Toretto.doGet(e); }
/** The page's API calls. */
function api(method, url, body) { return Toretto.api(method, url, body); }
function apiBatch(calls) { return Toretto.apiBatch(calls); }
/** Timed jobs (setup() schedules them). */
function sendQueuedEmails() { return Toretto.sendQueuedEmails(); }
function runHourlyJobs() { Toretto.runHourlyJobs(); }

`;

// ---- index.html --------------------------------------------------------------
async function buildPage() {
  await vite({ configFile: here('./vite.config.ts'), logLevel: 'warn' });
  const built = here('./.client-build');
  let page = readFileSync(`${built}/index.html`, 'utf8');
  const asset = (href) => readFileSync(`${built}/${href.replace(/^\.\//, '')}`, 'utf8');
  // Inline scripts must not contain "</script" or "<!--" (they'd end or confuse the tag).
  const safeScript = (js) => js.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
  page = page
    .replace(
      /<script type="module" crossorigin src="([^"]+)"><\/script>/,
      (_, src) => `<script type="module">${safeScript(asset(src))}</script>`,
    )
    .replace(
      /<link rel="stylesheet" crossorigin href="([^"]+)">/,
      (_, href) => `<style>${asset(href).replace(/<\/style/gi, '<\\/style')}</style>`,
    )
    .replace(
      '<!--TORETTO_THEME-->',
      // Line endings as in git, not as this machine checked the file out.
      `<script>${normalizeLineEndings(readFileSync(here('../web/public/theme.js'), 'utf8'))}</script>`,
    );
  if (/\s(src|href)="\.\/assets\//.test(page)) {
    throw new Error('index.html still points at a separate asset file');
  }
  if (!page.includes('<!--TORETTO_BOOT-->'))
    throw new Error('index.html lost the boot placeholder');
  if (!page.includes(`<meta name="toretto-version" content="${VERSION}"`)) {
    throw new Error('index.html lost its version tag');
  }
  // Every API call must go through google.script.run, not the web server's fetch client.
  if (page.includes('same-origin') || !page.includes('sendQueuedEmails')) {
    throw new Error("The web app's fetch-based API client ended up in the Apps Script page");
  }
  rmSync(built, { recursive: true, force: true });
  return normalizeLineEndings(page);
}

// Run as a script (not imported by the tests): write the three files.
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const server = await buildServer();
  const page = await buildPage();
  const version = createHash('sha256').update(server).update(page).digest('hex').slice(0, 8);
  const out = here('./build');
  mkdirSync(out, { recursive: true });
  writeFileSync(`${out}/Code.gs`, stamp(server, version));
  writeFileSync(`${out}/index.html`, stamp(page, version));
  copyFileSync(here('./appsscript.json'), `${out}/appsscript.json`);
  console.log(`Version ${version}`);
  for (const file of readdirSync(out)) {
    const kb = Math.round(readFileSync(`${out}/${file}`).length / 1024);
    console.log(`apps-script/build/${file}  ${kb} KB`);
  }
}
